### ISSUE TITLE
Should Expr allow override built-in functions with user defined ones?

### ISSUE THREAD

**Issue by antonmedv** [expr-lang/expr#507]
It will be easier to work with Expr as dev. We still can give access to builtins with `::` global scope C++ style syntax. 

```go
	env := map[string]interface{}{
		"string":   "my string",
	}

	code := `string + ::string(42)`

	program, err := expr.Compile(code, expr.Env(env))
}
```

**Comment by antonmedv** [comment]
Yes. See #520

**Comment by agilgur5** [comment]
For posterity, #520 was filed as a result of https://github.com/argoproj/argo-workflows/issues/12037, which was a [regression](https://github.com/argoproj/argo-workflows/issues/12037#issuecomment-1771076883) from previous behavior. Since the new built-ins and type checks were released in a minor, the previous behavior should remain, which is what skewed the decision here.
