### ISSUE TITLE
Allow to override builtins with user env

### ISSUE THREAD

**Issue by isubasinghe** [expr-lang/expr#520]
There are scenarios where `Eval` is called with keywords being present in the expression itself. 
These can fail because of the type checking. 

```go

func nameclash() {
  env := make[string]any{
    "foo": 1,
    "split": 2
  }
  output, err := expr.Eval("foo + split", env)
  if err != nil {
    // currently this branch will be reached
    return;
  }
}
```

**Comment by antonmedv** [comment]
Yes, I now I think it is clear what it is better to allow override built-in function with any env variables.

**Comment by agilgur5** [comment]
For posterity, this was filed as a result of https://github.com/argoproj/argo-workflows/issues/12037, which was a [regression](https://github.com/argoproj/argo-workflows/issues/12037#issuecomment-1771076883) from previous behavior. Since the new built-ins and type checks were released in a minor, the previous behavior should remain, which is what skewed the decision in favor.
